package cz.filmtit.share;

import com.google.gwt.user.client.rpc.IsSerializable;

import java.io.Serializable;
import java.util.*;
public class Document implements IsSerializable, Serializable {
    public long spentOnThisTime;

    // Generated by Userspace (i.e. probably by the database)
    private long id = Long.MIN_VALUE;
    private MediaSource movie;
    private Language language;

    private long userId = Long.MIN_VALUE;

    public TreeMap<ChunkIndex, TranslationResult> translationResults = new TreeMap<ChunkIndex, TranslationResult>();
    
	public Document() {
    	// nothing
    }

    public Document(String movieTitle, String year, String langCode) {
		movie = new MediaSource(movieTitle, year);
		this.language = Language.fromCode(langCode);
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
        if (this.id == id) { return; }
        if (this.id != Long.MIN_VALUE) {
            throw new UnsupportedOperationException("Once the document ID is set, it cannot be changed.");
        }
        this.id = id;
	}

    public MediaSource getMovie() {
        return movie;
    }

    public void setMovie(MediaSource movie) {
        this.movie = movie;
    }

    public Language getLanguage() {
        return language;
    }

    public void setLanguageCode(String languageCode) {
        language = Language.fromCode(languageCode);
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        if (this.userId == userId) { return; }
        if (this.userId != Long.MIN_VALUE) {
            throw  new UnsupportedOperationException("Once the owner ID is set, it cannot be changed.");
        }
        this.userId = userId;
    }

    public List<TranslationResult> getSortedTranslationResults() {
       List<TranslationResult> res = new ArrayList<TranslationResult>(translationResults.size());
       //sorted because treeset
       for (ChunkIndex i:translationResults.keySet()) {
          res.add(translationResults.get(i));
       }
       return res;
    }

    public Map<ChunkIndex, TranslationResult> getTranslationResults() {
        return translationResults;
    }

}
