package cz.filmtit.share;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

public class Document implements Serializable {
    public String movieTitle;
    public int year;
    public long spentOnThisTime;
    public String language;
    
    // Generated by Userspace (i.e. probably by the database)
    private long id;

    public List<TranslationResult> translationResults = new ArrayList<TranslationResult>();
    
	public Document() {
    	// nothing
    }

    public Document(String movieTitle, int year, String language) {
		this.movieTitle = movieTitle;
		this.year = year;
		this.language = language;
	}

	public long getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
