package cz.filmtit.share;
import java.io.Serializable;


import java.io.Serializable;

public class TimedChunk extends Chunk implements com.google.gwt.user.client.rpc.IsSerializable, Serializable {
	// TODO: should be long - probably number of milliseconds 
	private String startTime;
    private String endTime;
    private int partNumber;

    // Generated by GUI
    private int id = Integer.MIN_VALUE;
    
    // Document.id
    private long documentId = Long.MIN_VALUE;

    public TimedChunk() {
    	// nothing;    	
    }
    
    public TimedChunk(String startTime, String endTime, int partNumber, String text, int id, long documentId) {
        super(text);
        this.startTime = startTime;
        this.endTime = endTime;
        this.partNumber = partNumber;
		this.id = id;
		this.documentId = documentId;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public int getPartNumber() {
        return partNumber;
    }

    public void setPartNumber(int partNumber) {
        this.partNumber = partNumber;
    }

	public int getId() {
		return id;
	}

    public void setId(int id) {
        if (this.id != Integer.MIN_VALUE) {
            throw new UnsupportedOperationException("Once the timed chunk ID is set, it cannot be changed.");
        }
        this.id = id;
    }

	public long getDocumentId() {
		return documentId;
	}

    public void setDocumentId(long documentId) {
        if (this.documentId != Long.MIN_VALUE) {
            throw new UnsupportedOperationException("Once the parent document ID is set, it cannot be changed.");
        }
        this.documentId = documentId;
    }
}
