package cz.filmtit.share;

import java.io.Serializable;

public class TimedChunk extends Chunk implements Serializable {
	private String startTime;
    private String endTime;
    private int partNumber;

    // Generated by GUI
    private int id;
    
    // Document.id
    private long documentId;

    public TimedChunk() {
    	// nothing;    	
    }
    
    public TimedChunk(String startTime, String endTime, int partNumber, String text, int id, long documentId) {
        super(text);
        this.startTime = startTime;
        this.endTime = endTime;
        this.partNumber = partNumber;
		this.id = id;
		this.documentId = documentId;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public int getPartNumber() {
        return partNumber;
    }

    public void setPartNumber(int partNumber) {
        this.partNumber = partNumber;
    }

	public int getId() {
		return id;
	}

	public long getDocumentId() {
		return documentId;
	}
}
